# Generated by Django 4.2.2 on 2023-06-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tododb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('time_created', models.DateField(auto_now_add=True)),
                ('time_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
